#pragma once

#include "NativeGameplayTags.h"

namespace FVNavigationTags
{
	// Ids of map definitions.
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Map);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Map_World);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Map_Region);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Map_Interior);

	// Ids of marker definitions.
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Type);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Type_Waypoint);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Type_QuestTarget);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Type_QuestGiver);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Type_PointOfInterest);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Type_Shop);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Type_FastTravel);

	// Marker categories (definition Tags), used by legend filters.
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Category);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Category_Player);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Category_Quest);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Category_Exploration);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Category_Service);
	FVNAVIGATIONSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Marker_Category_Travel);
}
