;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.Action.Greet",NewTagName="Character.Action.Character.Action.Social.Greet")
+GameplayTagRedirects=(OldTagName="Character.Action.Sex.Anal",NewTagName="Character.Action.Sex.Act.Anal")
+GameplayTagRedirects=(OldTagName="InputTag.Ability.Iteract",NewTagName="InputTag.Ability.Interact")
+GameplayTagRedirects=(OldTagName="Interaction.Action.Pay",NewTagName="Interaction.Action.PayMoney")
+GameplayTagList=(Tag="Ability.Interaction.Talk",DevComment="")
+GameplayTagList=(Tag="Action",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Handplant",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Jump",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Land",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Run",DevComment="")
+GameplayTagList=(Tag="Foley.Event.RunBackwds",DevComment="")
+GameplayTagList=(Tag="Foley.Event.RunStrafe",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Scuff",DevComment="")
+GameplayTagList=(Tag="Foley.Event.ScuffPivot",DevComment="")
+GameplayTagList=(Tag="Foley.Event.ScuffWall",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Slide.Loop",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Tumble",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Walk",DevComment="")
+GameplayTagList=(Tag="Foley.Event.WalkBackwds",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability.Focus",DevComment="Focus ability input")
+GameplayTagList=(Tag="InputTag.Ability.Interact",DevComment="")
+GameplayTagList=(Tag="InputTag.Inventory",DevComment="")
+GameplayTagList=(Tag="Interactable.Character.Bartender",DevComment="")
+GameplayTagList=(Tag="Interactable.Character.Dealer",DevComment="")
+GameplayTagList=(Tag="Interaction.Action.CallOut",DevComment="")
+GameplayTagList=(Tag="Interaction.Action.Sex",DevComment="")
+GameplayTagList=(Tag="Interaction.Event.InteractionZoneEnter",DevComment="")
+GameplayTagList=(Tag="Interaction.Event.InteractionZoneExit",DevComment="")

