// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Logging/LogMacros.h"

/**
 * FlickerVoid Log Categories
 * Centralized declaration of all log categories used across the project
 */

// Core System Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVCore, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVSystem, Log, All);

// Character Module Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVCharacter, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVMovement, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVAnimation, Log, All);

// AI Module Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVAI, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVBehavior, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVPerception, Log, All);

// Gameplay Module Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVGameplay, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVAbility, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVCombat, Log, All);

// Items Module Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVItems, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVInventory, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVEquipment, Log, All);

// Narrative Module Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVNarrative, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVDialogue, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVQuest, Log, All);

// UI Module Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVUI, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVHUD, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVMenu, Log, All);

// World Module Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVWorld, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVEnvironment, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVStreaming, Log, All);

// Input & Physics Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVInput, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVPhysics, Log, All);

// Network Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVNetwork, Log, All);
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVReplication, Log, All);

// Save/Load System Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVSave, Log, All);

// Audio Logging
FLICKERVOIDCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogFVAudio, Log, All);
